JobOpportunities/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JobOpportunities.Models;

namespace JobOpportunities.Controllers
{

    [Authorize(Roles ="Admins")]
    public class CategoryController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Category
        [AllowAnonymous]
        public ActionResult Index()
        {
            return View(db.Categories.ToList());
        }

        // GET: Category/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // GET: Category/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Category/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CategoryID,CategoryName,CategoryDescription")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Categories.Add(category);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(category);
        }

        // GET: Category/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Category/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CategoryID,CategoryName,CategoryDescription")] Category category)
        {
            if (ModelState.IsValid)
            {
                db.Entry(category).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(category);
        }

        // GET: Category/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return View(category);
        }

        // POST: Category/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Category category = db.Categories.Find(id);
            db.Categories.Remove(category);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

JobOpportunities/Controllers/JobController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JobOpportunities.Models;
using System.IO;
using Microsoft.AspNet.Identity;

namespace JobOpportunities.Controllers
{

    [Authorize]
    public class JobController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        [AllowAnonymous]
        // GET: Job
        public ActionResult Index()
        {
            var jobs = db.Jobs.Include(j => j.Category);
            return View(jobs.ToList());
        }

       


        // GET: Job/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job job = db.Jobs.Find(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            return View(job);
        }



        // GET: Job/Create

        public ActionResult Create()
        {
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "CategoryName");
            return View();
        }

        // POST: Job/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "JobID,JobTitle,JobContent,JobImage,CategoryID")] Job job, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                //    1                  1                                    111                               222
                // Path class       combine => to bind 2 paths   ( server.mapPath ( path on project ) , upload.FileName == image name )
                string path = Path.Combine(Server.MapPath("~/Images/Jobs/"), upload.FileName);
                upload.SaveAs(path);              // then put path which saved the path on it    up
                job.JobImage = upload.FileName;   // jobImage from   object job     to save path on database
                job.UserId = User.Identity.GetUserId();

                db.Jobs.Add(job);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "CategoryName", job.CategoryID);
            return View(job);
        }




        // GET: Job/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job job = db.Jobs.Find(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "CategoryName", job.CategoryID);
            return View(job);
        }

        // POST: Job/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "JobID,JobTitle,JobContent,JobImage,CategoryID")] Job job, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                // another variable  to store the last  path  and delete  the last image if you put another image by the next code
                string oldPath = Path.Combine(Server.MapPath("~/Images/Jobs"), job.JobImage);

                if (upload != null)
                {
                    //if you put another image            delete the last image from server
                    System.IO.File.Delete(oldPath);
                    string path = Path.Combine(Server.MapPath("~/Images/Jobs"), upload.FileName);
                    upload.SaveAs(path);
                    job.JobImage = upload.FileName;
                   
                }
                 
                 
                db.Entry(job).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "CategoryName", job.CategoryID);
            return View(job);
        }





        // GET: Job/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job job = db.Jobs.Find(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            return View(job);
        }



        // POST: Job/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Job job = db.Jobs.Find(id);
            db.Jobs.Remove(job);
            db.SaveChanges();
            return RedirectToAction("Index");
        }




        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

JobOpportunities/Controllers/RoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using JobOpportunities.Models;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Data.Entity;
namespace JobOpportunities.Controllers
{

    public class RoleController : Controller
    {

        ApplicationDbContext db = new ApplicationDbContext();
        // GET: Role
        public ActionResult Index()
        {
            return View(db.Roles.ToList());
        }




        // GET: Role/Details/5
        public ActionResult Details(string id)
        {
            var role = db.Roles.Find(id);
            if (role == null)
            {
                return HttpNotFound();
            }

            return View(role);
        }






        // GET: Role/Create
        public ActionResult Create()
        {
            return View();
        }


        // POST: Role/Create
        [HttpPost]
        public ActionResult Create(IdentityRole role)
        {
            if (ModelState.IsValid)
            {
                db.Roles.Add(role);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(role);


        }






        // GET: Role/Edit/5
        public ActionResult Edit(string id)
        {
            var role = db.Roles.Find(id);
            if (role == null)
            {
                return HttpNotFound();
            }
            return View(role);
        }

        // POST: Role/Edit/5
        [HttpPost]
        public ActionResult Edit([Bind(Include = "Id,Name")]IdentityRole role)
        {

            if (ModelState.IsValid)
            {
                // We use this code in Editting
                db.Entry(role).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(role);
        }





        // GET: Role/Delete/5
        public ActionResult Delete(string id)
        {
            var role = db.Roles.Find(id);
            if (role == null)
            {
                return HttpNotFound();
            }

            return View(role);
        }


        // POST: Role/Delete/5
        [HttpPost]
        public ActionResult Delete([Bind(Include = "Id,Name")] IdentityRole role)
        {
            // we put variable to find the role by    role.id   and delete the variable
            var del = db.Roles.Find(role.Id);
            db.Roles.Remove(del);
            db.SaveChanges();

            return RedirectToAction("Index");
        }




    }
}

JobOpportunities/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    @* viewport for responsive for mobiles               initial scale=1 for zoom *@
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Job Opportunities</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">

                @*<a class="navbar-brand ">
                    <img src="~/Images/logo.png" width="75" height="50"/>
                </*@


                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Job Opportunities", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    @*<li>@Html.ActionLink("Categories", "Index", "Category")</li>*@
                    @*<li>@Html.ActionLink("Jobs", "Index", "Job")</li>*@
                    @*<li>@Html.ActionLink("Roles", "Index", "Role")</li>*@
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("ContactUs", "Contact", "Home")</li>
                 
                    <li>
                        @using (Html.BeginForm("Search", "Home", FormMethod.Post))
                        {
                            <input type="text" name="SearchName" id="SearchName" placeholder="Search here" />
                        }
                    </li>
                    

                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>

    <div class="container body-content">
        <div class="row" style="min-height: 550px;">
            @RenderBody()
        </div>
    </div>


    <hr />



    <footer class="navbar navbar-inverse text-muted myfooter">
        <br />
        <div class="container">
            <div class="row">

                <div class="col-md-4 foot">
                    <h3>
                        <i class="glyphicon glyphicon-question-sign"></i>
                        Who are us ?
                    </h3>
                    <p>
                        In the previous tutorial you displayed related data. In this tutorial you'll
                        update related data. For most relationships,
                        this can be done by updating either foreign key fields or
                    </p>
                </div>
                <div class="col-md-4 foot">
                    <h3>
                        <i class="glyphicon glyphicon-globe"></i>
                        Important links
                    </h3>
                    <ul>
                        <li><a href="#">Public sector jobs</a></li>
                        <li><a href="#">Private sector jobs</a></li>
                        <li><a href="#">Jobs abroad</a></li>
                        <li><a href="#">Miscellaneous jobs</a></li>
                    </ul>
                </div>
                <div class="col-md-4 foot">
                    <h3>
                        <i class="glyphicon glyphicon-envelope"></i>
                        Contact Us
                    </h3>
                    <ul>
                        <li><a href="#">Our facebook page</a></li>
                        <li><a href="#">Follow us on twitter</a></li>
                        <li><a href="#">Subscribe us om Youtube</a></li>
                        <li><a href="#">Send a message</a></li>
                    </ul>
                </div>
            </div>
            <div class="row text-center subfooter">
                <hr />
                <p>Al rights reserved to the recruiment site.</p>
                <p>&copy; @DateTime.Now.Year - Job Opportunities</p>
            </div>
        </div>
    </footer>



    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>