JobOpportunities/Models/ApplyForJob.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace JobOpportunities.Models
{
    public class ApplyForJob
    {
        public int Id { get; set; }
        public string Message { get; set; }
        public string Resume { get; set; }
        public DateTime ApplyDate { get; set; }

        // FK
        public int JobId { get; set; }
        public string UserId { get; set; }



        // Navigation properties
        public virtual Job Job { get; set; }
        public virtual ApplicationUser User { get; set; }


    }
}

JobOpportunities/Controllers/ApplyForJobController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JobOpportunities.Models;
using Microsoft.AspNet.Identity;
using System.IO;

namespace JobOpportunities.Controllers
{
    public class ApplyForJobController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();


        [Authorize]
        public ActionResult Apply(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job job = db.Jobs.Find(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            Session["JobId"] = id;

            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        // Here When User Click Apply  We Will have  4 things    (UserId - JobId  -  Message  -  ApplyDate )
        public ActionResult Apply([Bind(Include = "Message,Resume")] ApplyForJob job, HttpPostedFileBase upload)
        {
            // GetUserId   is a method  return   user id but he must be login
            var userId = User.Identity.GetUserId();
            var jobId = (int)Session["JobId"];      // Here I did casting to session to save int from it

            // check if the user applied for this job  or  not
            var check = db.ApplyForJobs.Where(a => a.JobId == jobId && a.UserId == userId).ToList();
            if (check.Count < 1)
            {
                var path = Path.Combine(Server.MapPath("~/Images/CV"), upload.FileName);
                upload.SaveAs(path);
                job.Resume = upload.FileName;


                // create an  object  from   ApplyForJob  Class     and   give its properties  ==>> there values
                job.UserId = userId;
                job.JobId = jobId;
                job.ApplyDate = DateTime.Now;

                if (ModelState.IsValid)
                {
                    // Add the   object to database    and save changes
                    db.ApplyForJobs.Add(job);
                    db.SaveChanges();
                    ViewBag.Result = "Apllying is succeeded";
                }

            }
            else
            {
                ViewBag.Result = "Sorry , You already applied for this job";
            }



            return View();
        }




        [Authorize]
        public ActionResult GetJobsByUser()
        {
            var userId = User.Identity.GetUserId();
            var jobs = db.ApplyForJobs.Where(a => a.UserId == userId);

            return View(jobs.ToList());


        }


        [Authorize]
        public ActionResult DetailsOfJob(int id)
        {
            var job = db.ApplyForJobs.Find(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            return View(job);
        }

        public ActionResult EditJob(int id)
        {
            var job = db.ApplyForJobs.Find(id);
            if (job == null)
            {
                return HttpNotFound();
            }

            return View(job);
        }
        [HttpPost]

        public ActionResult EditJob(ApplyForJob job, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                string oldPath = Path.Combine(Server.MapPath("~/Images/CV"), job.Resume);

                if (upload != null)
                {
                    System.IO.File.Delete(oldPath);
                    string path = Path.Combine(Server.MapPath("~/Images/CV"), upload.FileName);
                    upload.SaveAs(path);
                    job.Resume = upload.FileName;

                }
            
                job.ApplyDate = DateTime.Now;
                db.Entry(job).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("GetJobsByUser");

            }
            return View(job);
        }
        //public ActionResult EditJob([Bind(Include = "Message,ApplyDate,Resume")] ApplyForJob job , HttpPostedFileBase upload)
        //{

        //    if (ModelState.IsValid)
        //    {

        //        string oldPath = Path.Combine(Server.MapPath("~/Images/CV"), job.Resume);

        //        if (upload != null)
        //        {
        //            System.IO.File.Delete(oldPath);
        //            string path = Path.Combine(Server.MapPath("~/Images/CV"), upload.FileName);
        //            upload.SaveAs(path);
        //            job.Resume = upload.FileName;

        //        }

        //        job.ApplyDate = DateTime.Now;
        //        db.Entry(job).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("GetJobsByUser");
        //    }

        //    return View(job);

        //}


        public ActionResult DeleteJob(int id)
        {
            var job = db.ApplyForJobs.Find(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            return View(job);

        }

        [HttpPost, ActionName("DeleteJob")]

        public ActionResult DeleteConfirm(int id)
        {
            var myJob = db.ApplyForJobs.Find(id);
            db.ApplyForJobs.Remove(myJob);
            db.SaveChanges();
            return RedirectToAction("GetJobsByUser");
        }





        // For Publisher
        //=======================================================================================


        [Authorize]
        public ActionResult GetJobsByPublisher()
        {

            var userId = User.Identity.GetUserId();


            var jobs = from app in db.ApplyForJobs
                       join job in db.Jobs
                       on app.JobId equals job.JobID
                       where job.UserId == userId
                       select app;


            var grooped = from j in jobs
                          group j by j.Job.JobTitle
                          into gr
                          select new JobsViewModel
                          {
                              JobTitle = gr.Key,
                              Items = gr
                          };
            return View(grooped.ToList());
        }





        public ActionResult DetailsApplyer(int id)
        {


            ApplyForJob job = db.ApplyForJobs.Find(id);
            if (job == null)
            {
                return HttpNotFound();
            }

            return View(job);
        }








        [Authorize]
        public ActionResult AllMyPostedJobs()
        {

            var userId = User.Identity.GetUserId();
            var jobs = db.Jobs.Where(a => a.UserId == userId).ToList();

            return View(jobs);
        }
























        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

JobOpportunities/Controllers/JobController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JobOpportunities.Models;
using System.IO;
using Microsoft.AspNet.Identity;

namespace JobOpportunities.Controllers
{

    [Authorize]
    public class JobController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        [AllowAnonymous]
        // GET: Job
        public ActionResult Index()
        {
            var jobs = db.Jobs.Include(j => j.Category);
            return View(jobs.ToList());
        }

       


        // GET: Job/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job job = db.Jobs.Find(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            return View(job);
        }



        // GET: Job/Create

        public ActionResult Create()
        {
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "CategoryName");
            return View();
        }

        // POST: Job/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "JobID,JobTitle,JobContent,JobImage,CategoryID")] Job job, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                //    1                  1                                    111                               222
                // Path class       combine => to bind 2 paths   ( server.mapPath ( path on project ) , upload.FileName == image name )
                string path = Path.Combine(Server.MapPath("~/Images/Jobs/"), upload.FileName);
                upload.SaveAs(path);              // then put path which saved the path on it    up
                job.JobImage = upload.FileName;   // jobImage from   object job     to save path on database
                job.UserId = User.Identity.GetUserId();

                db.Jobs.Add(job);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "CategoryName", job.CategoryID);
            return View(job);
        }




        // GET: Job/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job job = db.Jobs.Find(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "CategoryName", job.CategoryID);
            return View(job);
        }

        // POST: Job/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "JobID,JobTitle,JobContent,JobImage,CategoryID")] Job job, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                // another variable  to store the last  path  and delete  the last image if you put another image by the next code
                string oldPath = Path.Combine(Server.MapPath("~/Images/Jobs"), job.JobImage);

                if (upload != null)
                {
                    //if you put another image            delete the last image from server
                    System.IO.File.Delete(oldPath);
                    string path = Path.Combine(Server.MapPath("~/Images/Jobs"), upload.FileName);
                    upload.SaveAs(path);
                    job.JobImage = upload.FileName;
                   
                }
                 
                 
                db.Entry(job).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryID = new SelectList(db.Categories, "CategoryID", "CategoryName", job.CategoryID);
            return View(job);
        }





        // GET: Job/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Job job = db.Jobs.Find(id);
            if (job == null)
            {
                return HttpNotFound();
            }
            return View(job);
        }



        // POST: Job/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Job job = db.Jobs.Find(id);
            db.Jobs.Remove(job);
            db.SaveChanges();
            return RedirectToAction("Index");
        }




        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

JobOpportunities/Views/ApplyForJob/AllMyPostedJobs.cshtml
@model IEnumerable<JobOpportunities.Models.Job>

@{
    ViewBag.Title = "AllMyPostedJobs";
}

<h2>All My Posted Jobs</h2>

<p>
    @Html.ActionLink("Create New", "Create","Job")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Category.CategoryName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.JobTitle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.JobContent)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.JobImage)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Category.CategoryName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.JobTitle)
        </td>
        <td>
            @Html.Raw(HttpUtility.HtmlDecode(Html.DisplayFor(modelItem => item.JobContent).ToString()))

        </td>
        <td>
           <img src="~/Images/Jobs/@Html.DisplayFor(modelItem => item.JobImage)" style="width:70px; height:90px" class="thumbnail"/> 
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit","Job", new { id=item.JobID } , null) |
            @Html.ActionLink("Details", "Details","job", new { id=item.JobID }, null) |
            @Html.ActionLink("Delete", "Delete","Job", new { id=item.JobID } , null)
        </td>
    </tr>
}

</table>

JobOpportunities/Views/ApplyForJob/Apply.cshtml
@model JobOpportunities.Models.ApplyForJob

@{
    ViewBag.Title = "Apply";
}

<div class="row">
    <h2 class="panel-heading text-center" style="background-color:darkgray">Apply for job</h2>
    <hr />
</div>


@using (Html.BeginForm("Apply", "ApplyForJob",FormMethod.Post,  new { enctype = "multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
       
        <div class="row">
            @{ 
                if(ViewBag.Result != null)
                {
                    <h3 class="text-success">@ViewBag.Result</h3>
                }
            }
        <hr />
        </div>

        

            <div class="row">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                <div class="form-group">
                    @Html.LabelFor(model => model.Message, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextAreaFor(model => model.Message, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Message, "", new { @class = "text-danger" })
                    </div>
                </div>


                <div class="form-group">
                    @Html.LabelFor(model => model.Resume, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        <input type="file" name="upload"/>
                        @Html.ValidationMessageFor(model => model.Resume, "", new { @class = "text-danger" })
                    </div>
                </div>

            </div>
        
        


        <div class="form-group row">
            <div class="col-md-offset-1 col-md-10">
                <input type="submit" value="Send And Apply" class="btn btn-success" />
                @Html.ActionLink("Back To Home", "Index","Home" ,null, new { @class="btn btn-warning"})
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

JobOpportunities/Views/ApplyForJob/DeleteJob.cshtml
@model JobOpportunities.Models.ApplyForJob

@{
    ViewBag.Title = "DeleteJob";
}

<h2>DeleteJob</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ApplyForJob</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Job.JobTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Job.JobTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Message)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Message)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ApplyDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApplyDate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            @Html.ActionLink("Back to List", "GetJobsByUser")
        </div>
    }
</div>

JobOpportunities/Views/ApplyForJob/DetailsApplyer.cshtml
@model JobOpportunities.Models.ApplyForJob

@{
    ViewBag.Title = "DetailsApplyer";
}

<h2>DetailsApplyer</h2>

<div>
    <h4>ApplyForJob</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.User.UserName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.UserName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Job.JobTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Job.JobTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Message)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Message)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Resume)
        </dt>

        <dd>
            <embed src="~/Images/CV/@Html.DisplayFor(model => model.Resume)"/> 
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ApplyDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApplyDate)
        </dd>

    </dl>
</div>
<p>
    
    @Html.ActionLink("Back to List", "GetJobsByPublisher")
</p>

JobOpportunities/Views/ApplyForJob/DetailsOfJob.cshtml
@model JobOpportunities.Models.ApplyForJob

@{
    ViewBag.Title = "DetailsOfJob";
}

<h2>DetailsOfJob</h2>

<div>
    
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Job.JobTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Job.JobTitle)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Resume)
        </dt>

        <dd>
           <embed src="~/Images/CV/@Html.DisplayFor(model => model.Resume)"/> 
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Message)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Message)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ApplyDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApplyDate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "GetJobsByUser")
</p>

JobOpportunities/Views/ApplyForJob/EditJob.cshtml
@model JobOpportunities.Models.ApplyForJob

@{
    ViewBag.Title = "EditJob";
}

<h2>Edit Job</h2>


@using (Html.BeginForm("EditJob", "ApplyForJob", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ApplyForJob</h4>
        

        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.JobId)
        @Html.HiddenFor(model => model.UserId)




        <div class="form-group">
            @Html.LabelFor(model => model.Resume, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @if (string.IsNullOrWhiteSpace(Model.Resume))
                {
                    <input type="file" name="upload" />
                }
                else
                {
                    <embed src="~/Images/CV/@Html.DisplayFor(model => model.Resume)" class="thumbnail" />
                    <input type="file" name="upload" />
                }
                @Html.ValidationMessageFor(model => model.Resume, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Message, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Message, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Message, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ApplyDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Model.ApplyDate
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.JobId, "Job Title", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Model.Job.JobTitle
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserId, "User Name", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Model.User.UserName
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "GetJobsByUser")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

JobOpportunities/Views/ApplyForJob/GetJobsByPublisher.cshtml
@model IEnumerable<JobOpportunities.Models.JobsViewModel>




<table class="table table-bordered">

    @foreach (var item in Model)
    {

        <tr>
            <th colspan="5" style="background-color:darkgray;"><h3>@item.JobTitle</h3> </th>
        </tr>

        <tr>
            <th>
                Applyer Name
            </th>
            <th>
                Resume
            </th>
            <th>
                Message
            </th>
            <th>
                Apply Date
            </th>
            <th></th>
        </tr>
        foreach (var x in item.Items)
        {
            <tr>
                <td>
                    @x.User.UserName
                </td>
                <td>
                    <embed src="~/Images/CV/@x.Resume" alt="Alternate Text" />
                </td>
                <td>
                    @x.Message
                </td>
                <td>
                    @x.ApplyDate
                </td>
                <td>
                    @Html.ActionLink("Select","DetailsApplyer" , new { id = x.Id})
                </td>
            </tr>
        }
        <tr style="background-color:black;">
            <td colspan="5">---------------------------</td>
        </tr>
        

    }
</table>

JobOpportunities/Views/ApplyForJob/GetJobsByUser.cshtml
@model IEnumerable<JobOpportunities.Models.ApplyForJob>

@{
    ViewBag.Title = "GetJobsByUser";
}

<h2>All jobs that you applied for</h2>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Job.JobTitle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Message)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Resume)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ApplyDate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Job.JobTitle)
        </td>
        <td>
           <embed src="~/Images/CV/@Html.DisplayFor(modelItem => item.Resume)" alt="pdf"/> 
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Message)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ApplyDate)
        </td>
        <td>
            @Html.ActionLink("Edit", "EditJob", new { id=item.Id }) |
            @Html.ActionLink("Details", "DetailsOfJob", new { id=item.Id }) |
            @Html.ActionLink("Delete", "DeleteJob", new { id=item.Id })
        </td>
    </tr>
}

</table>